// Cross-implementation parity: does this verifier accept a credential minted by
// the OTHER implementation?
//
// The rest of test/realmCredential.test.js mints with this code and verifies
// with this code. That proves self-consistency and cannot, even in principle,
// catch a divergence from the Dart reference at
// `tech_world:examples/livekit-token-server/lib/src/realm_credential_jwt.dart`
// — a codec can be self-consistently wrong. The two suites are near-mirror
// images down to the test names, which reads like agreement and is actually two
// independent self-checks.
//
// So this file verifies a token this repo did NOT produce, against a committed
// known-answer vector. The README's "a credential minted here verifies against
// that Dart verifier and vice versa" was an assertion until this existed.
//
// REGENERATING THE FIXTURE (the part you cannot derive by reading it):
//   1. openssl ecparam -name prime256v1 -genkey -noout -out k.pem
//      openssl pkcs8 -topk8 -nocrypt -in k.pem -out private.pem
//      openssl ec -in k.pem -pubout -out public.pem
//   2. In tech_world, `dart pub get`, then run a script that calls
//      RealmCredentialIssuer(signingKey: ECPrivateKey(pem), ttl: <long>)
//      .issue(subject: UserId('parity-vector-subject'),
//             provider: AuthProviderId('google'),
//             issuedAt: DateTime.utc(2026, 1, 1))
//   3. Commit the PUBLIC key and the token. NEVER the private key — tech_world's
//      gitleaks pre-commit gate blocks key material and it is right to.
//
// The keypair is throwaway and deployed nowhere. The long TTL is deliberate: a
// committed vector must not rot into a false red.
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

import {
  verifyRealmCredential,
  issueRealmCredential,
  RealmCredentialRejected,
} from '../src/realmCredential.js';
import { es256Keys } from './helpers.js';

const vector = JSON.parse(
  readFileSync(new URL('./fixtures/dart-minted-credential.json', import.meta.url), 'utf8'),
);

test('a credential minted by the Dart reference verifies here', () => {
  const claims = verifyRealmCredential(vector.publicKeyPem, vector.token);
  assert.equal(claims.subject, vector.expected.subject);
  assert.equal(claims.provider, vector.expected.provider);
});

// Guards the guard. If the fixture were ever regenerated by THIS implementation,
// the test above would silently become another self-round-trip — green, and
// blind to exactly what it exists to catch. The Dart issuer stamps `iat`; this
// one does not (asserted below), so the claim's presence is the cheapest
// available proof of foreign provenance.
test('the fixture is genuinely foreign, not a self-round-trip', () => {
  assert.equal(vector.header.alg, 'ES256');
  assert.ok(
    Object.hasOwn(vector.payload, 'iat'),
    'fixture has no iat — it may have been regenerated by this implementation; see the header comment',
  );
});

// The one real divergence found when the two were first run against each other
// (2026-08-20): the Dart issuer stamps `iat`, this one does not. Benign today —
// neither verifier requires it — and pinned here so it stays a known difference
// rather than a surprise. It stops being benign the moment either side adds an
// `iat`/`nbf` check or a max-age policy.
test('this implementation omits iat, and its own verifier accepts that', () => {
  // Ephemeral keypair, per this suite's existing discipline — no private key is
  // ever committed (test/helpers.js `es256Keys`).
  const { privateKeyPem, publicKeyPem } = es256Keys();
  const cred = issueRealmCredential(privateKeyPem, {
    subject: 'parity-vector-subject',
    provider: 'google',
    ttlSeconds: 3600,
  });
  const payload = JSON.parse(
    Buffer.from(cred.token.split('.')[1], 'base64url').toString(),
  );
  assert.equal(Object.hasOwn(payload, 'iat'), false);
  assert.doesNotThrow(() => verifyRealmCredential(publicKeyPem, cred.token));
});

// Red-proof that the vector is load-bearing: corrupt the signature and the
// acceptance above must become a refusal. Without this, a fixture that had
// rotted into garbage would still "pass" if verifyRealmCredential ever started
// failing open.
test('a tampered vector is refused — the check can go red', () => {
  const [h, p] = vector.token.split('.');
  const forged = `${h}.${p}.AAAA${'A'.repeat(82)}`;
  assert.throws(
    () => verifyRealmCredential(vector.publicKeyPem, forged),
    RealmCredentialRejected,
  );
});
